### ISSUE TITLE
Dynamically create element to display information on state.html

### ISSUE THREAD

**Issue by nguyen-william93** [nguyen-william93/Covid-Tourism-Information-Center#29]
AS A developer, I  WANT to dynamically create the elements to display on state.html SO THAT it can match each state. 
WHEN I click a state, THEN that state’s page is dynamically generated.

**Comment by izztnkr** [comment]
Closing issue: reformatting syntax of issue per Omar instructions.

**Comment by izztnkr** [comment]
Re-opening due to reformatting of issue syntax per Omar Instruction.


As a developer, I want to dynamically create the elements to display on state.html so that it can match each state.When I click a state, then that state’s page is dynamically generated.
